"""ConductivityContext: shared computation metadata for Calculator and Accumulator."""

from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np
from numpy.typing import NDArray

from phono3py.phonon.grid import BZGrid


@dataclass
class ConductivityContext:
    """Computation metadata shared by Calculator and Accumulator.

    This dataclass consolidates grid, phonon, symmetry, and configuration
    metadata that was previously scattered across Calculator and Accumulator
    constructors.  Both components receive a reference to the same context
    instance, eliminating redundant parameter passing and clarifying data
    ownership.

    Fields are treated as read-only after construction, with the exception
    of ``temperatures`` which may be updated when loading data from file.

    """

    # -- Grid metadata --

    grid_points: NDArray[np.int64]
    """BZ grid point indices that are iterated over.

    For RTA this may be user-specified grid points or the irreducible set.
    For LBTE this is always the irreducible set (same as ``ir_grid_points``).

    """

    ir_grid_points: NDArray[np.int64]
    """Irreducible BZ grid point indices."""

    grid_weights: NDArray[np.int64]
    """Symmetry weights for ``grid_points``."""

    bz_grid: BZGrid
    """BZ grid object."""

    mesh_numbers: NDArray[np.int64]
    """BZ mesh numbers, shape (3,)."""

    # -- Phonon data (full BZ) --

    frequencies: NDArray[np.double]
    """Phonon frequencies at all BZ grid points, shape (num_bzgp, num_band)."""

    eigenvectors: NDArray[np.cdouble]
    """Phonon eigenvectors at all BZ grid points."""

    # -- Symmetry operations --

    point_operations: NDArray[np.int64]
    """Reciprocal-space point-group operations, shape (num_ops, 3, 3)."""

    rotations_cartesian: NDArray[np.double]
    """Cartesian rotation matrices, shape (num_ops, 3, 3)."""

    # -- Configuration --

    temperatures: NDArray[np.double] | None
    """Temperatures in Kelvin, shape (num_temp,), or None if not yet set."""

    sigmas: list[float | None]
    """Smearing widths.  Empty list selects the tetrahedron method."""

    sigma_cutoff_width: float | None
    """Smearing cutoff in units of sigma."""

    boundary_mfp: float | None
    """Boundary mean free path in micrometres."""

    band_indices: NDArray[np.int64]
    """Band indices used for the calculation."""

    cutoff_frequency: float
    """Modes below this frequency (THz) are excluded."""

    # -- LBTE-specific (None for RTA) --

    rot_grid_points: NDArray[np.int64] | None = field(default=None)
    """Grid points generated by point-group rotations of ir_grid_points.

    Shape (num_ir_gp, num_ops).  None for RTA and reducible collision
    matrix mode.

    """
