name: Pytest with openblas and numpy 2.0

on:
  pull_request:
    branches: [ develop ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    # Use conda-incubator/setup-miniconda for precise control of conda infrastructure
    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
    - name: Install dependent packages
      run: |
        conda activate test
        conda install --yes python=${{ matrix.python-version }}
        conda install --yes matplotlib-base pyyaml "libblas=*=*openblas" openblas h5py "numpy=2" scipy pytest codecov pytest-cov cmake c-compiler
    - name: Install spglib develop branch
      run: |
        conda activate test
        git clone --depth 1 https://github.com/spglib/spglib.git
        cd spglib
        pip install -e . -vvv
        cd ..
    - name: Install symfc develop branch
      run: |
        conda activate test
        git clone --depth 1 https://github.com/symfc/symfc.git
        cd symfc
        pip install -e . -vvv
        cd ..
    - name: Install phonopy develop branch
      run: |
        conda activate test
        git clone --depth 1 https://github.com/phonopy/phonopy.git
        cd phonopy
        PHONOPY_USE_OPENMP=true pip install -e . -vvv
        cd ..
    - name: Install phono3py
      run: |
        conda activate test
        pip install -e . -vvv
    - name: Run pytest
      run: |
        pytest -v test
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        verbose: true
