name: Pytest without linking BLAS and LAPACK in C

on:
  pull_request:
    branches: [ develop ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    # Use conda-incubator/setup-miniconda for precise control of conda infrastructure
    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
    - name: Install dependent packages
      run: |
        conda activate test
        conda install --yes python=${{ matrix.python-version }}
        conda install --yes matplotlib-base pyyaml h5py scipy pytest spglib cmake c-compiler cxx-compiler
    - name: Install symfc develop branch
      run: |
        conda activate test
        git clone --depth 1 https://github.com/symfc/symfc.git
        cd symfc
        pip install -e . -vvv
        cd ..
    - name: Install phonopy develop branch
      run: |
        conda activate test
        git clone https://github.com/phonopy/phonopy.git
        cd phonopy
        pip install -e . -vvv
        cd ..
    - name: Install phono3py
      run: |
        conda activate test
        BUILD_WITHOUT_LAPACKE=ON pip install -e . -vvv
    - name: Run pytest
      run: |
        conda activate test
        pytest -v test
