name: Pytest on macOS

on:
  pull_request:
    branches: [ develop ]

jobs:
  build-macos:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: '3.13'
    - name: Install phonopy
      run: |
        pip install git+https://github.com/phonopy/phonopy@develop
    - name: Install phono3py
      run: |
        pip install -e . -v
    - name: Run pytest
      run: |
        pip install pytest
        pytest -v test
