name: publish phono3py gh-pages

on:
  push:
    branches: [publish-gh-pages]

jobs:
  docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        channels: conda-forge
        channel-priority: strict
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        conda activate test
        conda install --yes -c conda-forge python=${{ matrix.python-version }}
        conda install --yes -c conda-forge sphinx-book-theme linkify-it-py myst-parser sphinxcontrib-bibtex ipython
    - name: Build
      run: |
        conda activate test
        sphinx-build doc docs_build

    - name: Deploy docs at develop branch
      if: ${{ github.ref == 'refs/heads/publish-gh-pages' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs_build
        # deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
